spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web

lotto:
  result-checker:
    config:
      scheduler-cron: "0 55 11 * * 6"
  winning-numbers-generator:
    config:
      lowerBound: 1
      upperBound: 99
      requiredNumbers: 6
      generator-cron: "0 0 12 * * 6"

  http:
    client:
      config:
        uri: http://ec2-3-127-218-34.eu-central-1.compute.amazonaws.com
        port: 9090
        connectionTimeout: 5000
        readTimeout: 5000
        random-number-service-path: /api/v1.0/random