lotto:
  result-checker:
    config:
      scheduler-cron: "*/7 * * * * *"
  winning-numbers-generator:
    config:
      generator-cron: "*/5 * * * * *"
  jwt:
    config:
      secret: test-secret
      issuer: Lotto Service
      expirationDays: 365